version: 3

project:
  locator: solaceservices_CertificateManager
  id: solaceservices_CertificateManager
  name: CertificateManager
  teams: []
  labels:
    - python

vendoredDependencies:
  forceRescans: false
  scanMethod: CLILicenseScan
  licenseScanPathFilters:
    exclude:
      - "./.git"
      - "./.github"

paths:
  exclude:
    - ./.git
    - ./.github

telemetry:
  scope: full
